nameOverride: ""

fullnameOverride: ""

namespaceOverride: ""

global:
  additionalLabels: {}

  imagePullSecrets: []

  deploymentAnnotations: {}

  podAnnotations: {}

  podLabels: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

  env: []

deployment:
  image:
    repository: ghcr.io/huggingface/text-generation-inference
    tag: sha-96b7b40
    pullPolicy: IfNotPresent

  model: meta-llama/Meta-Llama-3-70B-Instruct

  resources:
    limits:
      nvidia.com/gpu: 1
    requests:
      cpu: 3
      memory: 10Gi

  tolerations:
  - key: nodepool
    operator: Equal
    value: llm
    effect: NoSchedule

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: role
            operator: In
            values:
            - llm





# model:
#   organization: TODO
#   name: TODO
#   huggingface_user: TODO
#   huggingface_token: TODO


# init:
#   image:
#     repository: TODO
#     tag: latest
#     pullPolicy: IfNotPresent
#   s3:
#     enabled: false
#     bucketURL: s3://TODO

# ingress:
#   enabled: false
